[deps]
CSTParser = "00ebfdb7-1f24-5e51-bd34-a7502290713f"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
HYPRE = "b5ffcf37-a2bd-41ab-a3da-4bd9bc8ad771"
JSONRPC = "b9b8584e-8fd3-41f9-ad0c-7255d428e418"
JUDI = "f3b833dc-6b2e-5b9c-b940-873ed6319979"
LanguageServer = "2b0e0bc5-e4fd-59b4-8912-456d1b03d8d7"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
StaticLint = "b3cc710f-9c33-5bdb-a03d-a94903873e97"
SymbolServer = "cf896787-08d5-524d-9de7-132aaa0cb996"
